### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ghost** [AGProjects/python-otr#2]
Is there any plan to add python 3 support?
Python 2 reached it's EOL over 2 years ago, and it'd be nice to have a version that supports python 3 instead

**Comment by saghul** [comment]
You probably want https://github.com/AGProjects/python3-otr

**Comment by ghost** [comment]
Is there any plan to publish the python 3 version to pypi?

**Comment by saghul** [comment]
Ping @adigeo :-)

**Comment by adigeo** [comment]
https://github.com/pypa/pypi-support/issues/2023

**Comment by ghost** [comment]
thanks!
